/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Checkbox from '../packages/checkbox/index.js';

const components = [
  Button,
  Checkbox
];

const install = function(Vue, opts = {}) {
	components.forEach(component => {
		Vue.component(component.name, component);
	})
}

if(typeof window !== 'undefined' && window.Vue) {
	install(window.Vue)
}

export default {
	version: '1.0.1',
	install,
  Button,
  Checkbox
}

