/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Dialog from '../packages/dialog/index.js';

const components = [
  Button,
  Dialog
];

const install = function(Vue, opts = {}) {
	components.forEach(component => {
		Vue.component(component.name, component);
	})
}

if(typeof window !== 'undefined' && window.Vue) {
	install(window.Vue)
}

export default {
	version: '1.0.0',
	install,
  Button,
  Dialog
}

